version: 2
registries:
  bytesafe:
    type: "python-index"
    url: "https://dependabot.bytesafe.dev/python/dependabot/"
    username: "bytesafe"
    password: ${{secrets.BYTESAFE_PASSWORD}}
    replaces-base: true
updates:
- package-ecosystem: pip
  directory: "/" # Update all dependencies
  registries:
    - bytesafe
  schedule:
    interval: "daily"
